### ISSUE TITLE
COMET results

### ISSUE THREAD

**Issue by puraminy** [allenai/comet-atomic-2020#10]
Could you please share or upload the COMET 2020 results files so that I can check the evaluation method you developed?
The file `automatic_eval.py` in `system_eval` contains the mentioned experiment files

**Comment by csbhagav** [comment]
Sorry for the delay in addressing the issues. We are looking at this and will respond soon.

**Comment by jeff-da** [comment]
The evaluation method used is from Alpha NLI: https://github.com/allenai/alpha-nli/.

We don't have a saved version of the results files -- they can be generated from `models/`. I added a modification on top of `automatic_eval.py` that'll make it easier to run. Let me know if there are more questions
