### ISSUE TITLE
How to use ATOMIC to generate commensense just like using the 'predict' button in your demo? 

### ISSUE THREAD

**Issue by Jingjie1218** [allenai/comet-atomic-2020#13]
Hi, I'm quite interested in the result of applying COMET on my own dataset. I've also checked your demo and found that I can do Commonsense Inferences about People and Events after entering a sentence and click 'predict'. But now I want to do inferences for plenty sentences, automatically, and in this case what should I do to edit corresponding py files to reach my goal? Looking forward to your replies!

**Comment by yana-xuyan** [comment]
Hi, did you figure out how to do that? If so, could you please give me a clue?
