### ISSUE TITLE
How to get .source and .target file at comet_atomic2020_bart

### ISSUE THREAD

**Issue by yongho94** [allenai/comet-atomic-2020#2]
Hello sir.

I tried to run your codes that use BART model to generate knowledge triples.

In your codes, "models/comet_atomic2020_bart/finetune.py" requires "train.source" file and "train.target" file...

However, I couldn't figure out how to get these files.

How can I get these files?

Thanks.

**Comment by RubenBranco** [comment]
Hi @yongho94,

I'm not one of the authors but I might be able to help here. The code expects a .source .target format that used to be the standard format for huggingface libraries before datasets came about. Here's the example page: https://github.com/huggingface/transformers/tree/master/examples/legacy/seq2seq

To produce this for comet, you iterate over the csv file and for each row you concatenate the head with the relation "{head} {rel}" and write to a "train.source" file, and then the tail is written to a train.target file, such that each row in the file correspond to each other.

Might be wrong though.

**Comment by yongho94** [comment]
> Hi @yongho94,
> 
> I'm not one of the authors but I might be able to help here. The code expects a .source .target format that used to be the standard format for huggingface libraries before datasets came about. Here's the example page: https://github.com/huggingface/transformers/tree/master/examples/legacy/seq2seq
> 
> To produce this for comet, you iterate over the csv file and for each row you concatenate the head with the relation "{head} {rel}" and write to a "train.source" file, and then the tail is written to a train.target file, such that each row in the files correspond to each other.
> 
> Might be wrong though.

Thanks @RubenBranco !!

It seems to be work. 

I think i need to try it.

Thanks.

**Comment by keisks** [comment]
Hi @yongho94, 

Thank you for your question. Regarding the data format for BART, @RubenBranco is correct.

The src and trg dataset (for BART) is available [here](https://storage.googleapis.com/ai2-mosaic-public/projects/mosaic-kgs/data_atomic_2020_BART-format.tgz). If you are also interested in the model we trained, you can get it from [here](https://storage.googleapis.com/ai2-mosaic-public/projects/mosaic-kgs/comet-atomic_2020_BART.zip)

I hope this helps!

**Comment by Kelaxon** [comment]
@keisks, Sorry for re-opening this, and thanks for the fantastic work.

I have another question regarding the data format:

I saw there are some "none" targets in the training, validating, and testing set. Why do you introduce them? Are they used to prevent over-fitting? If so, how do you determine the ratio and sampling method?

Thanks!
![image](https://user-images.githubusercontent.com/19503195/112773982-bdca0a80-906a-11eb-9c38-e7b118ea73cf.png)

**Comment by keisks** [comment]
The `none` targets mean that annotators answered there are no tails for given head and relation. In the dataset, we include all the annotations (=no sampling). As you can see, they are sometimes redundant because multiple annotators give same answers.

**Comment by Kelaxon** [comment]
Thanks for the explaination👍🏻
