### ISSUE TITLE
Missing files in system_eval

### ISSUE THREAD

**Issue by jyjohnchoi** [allenai/comet-atomic-2020#3]
Hello, I'm trying to run "automatic_eval.py" in "system_eval" directory to see its behavior.
However, it seems to require modules that are not included in "system_eval".

I found "utils.py" from "split/utils.py", but I couldn't find the "evaluation" module which you import in "automatic_eval.py"  (from evaluation.eval import QGEvalCap). 
Can you provide these files?

Also, can I know how the data (json file) that is used in "main()" can be obtained?

Thanks. 

--Edit--
I have found a repository at https://github.com/xinyadu/nqg which seems to include all required components.
Is this the right repository?

Thanks.

**Comment by jeffrey-da** [comment]
Hi @jyjohnchoi, thank you for your interest in our codebase.

For the data (json file), the json referenced is a combination of generated text (e.g. from https://github.com/allenai/comet-atomic-2020/blob/86b499b80244b9cb0f22342f3cf06bc247354787/models/comet_atomic2020_gpt2/comet_gpt2.py#L250) and the ATOMIC-2020 data as references. You may have to do some simple preprocessing to combine the two files together.

I added the eval files to the codebase!

**Comment by puraminy** [comment]
Your codebase isn't structured well. The modules and data are either absent or in folders other than the folders that are assumed by the code.
