### ISSUE TITLE
T5 Implemetation

### ISSUE THREAD

**Issue by puraminy** [allenai/comet-atomic-2020#5]
Do you have an implementation of COMET with T5? I have seen the following article mentioned it, but I couldn't find any code.

Understanding Few-Shot Commonsense Knowledge Models

Could you guide me on how I can change the current code to use T5? I've seen you declared T5 in some codes but you didn't use that.

Thanks

**Comment by jeff-da** [comment]
Hi, thank you for the interest. The T5 implementation can be found here: https://github.com/allenai/few-shot-comet

**Comment by jeff-da** [comment]
Closing for now, feel free to open if there's more questions
