### ISSUE TITLE
How to evaluate generated data

### ISSUE THREAD

**Issue by puraminy** [allenai/comet-atomic-2020#7]
When I tried to run:

```py eval.py --gen_file ../models/comet_atomic2020_gpt2/results/pred_generations.jsonl```

I got the following error:

```
Traceback (most recent call last):
  File "eval.py", line 139, in <module>
    sources, references, predictions = preprocess(args.gen_file, keys)
  File "eval.py", line 109, in preprocess
    keys_list = keys if keys!=None else generations[0]["generations"].keys()
AttributeError: 'list' object has no attribute 'keys'
```
What are keys? the generated list has no keys, 

You also pass keys to the evaluation, but what are them?

```python anli_evaluation/eval.py --gen_file GENERATIONS_FILE --keys MODEL_KEYS[comma-separated list] --results_file RESULTS_FILE```

I also checked `automatic_eval.py` in `system_eval`, it gets different types of input (type 1, 2, 3) none of which are according to the generated results. The generated results have `source`, `target`, and `generations` while the function expect other fields (such as `tails`, `head`, etc.)

**Comment by kosohae** [comment]
Could someone solve these problems?

**Comment by jeff-da** [comment]
Hi, thanks for the comment. For evaluation, you can use `system_eval/automatic_eval.py`. Please run as `python automatic_eval.py --input-file ../models/comet_atomic2020_gpt2/results/pred_generations.jsonl --type 4 --name gpt-2-comet`

**Comment by jeff-da** [comment]
Closing for now, please let me know if there are more questions about evaluation.
