### ISSUE TITLE
How do you calculate BLEU for short targets?

### ISSUE THREAD

**Issue by puraminy** [allenai/comet-atomic-2020#8]
The target or tail of many relations is short, for example it could be adjectives like `happy`, `satisfied` for `xReact` relation. How do you measure BLEU for these tails? As I read in the following implementation of BLEU

https://github.com/mjpost/sacrebleu/issues/150#issuecomment-808509500

The sentences must have at least 4 words so that it calculate BLEU. Moreover, because of the problems mentioned in previous issues I couldn't use `eval.py` to evaluate the generated lists by your code

**Comment by csbhagav** [comment]
Sorry for the delay in addressing the issues. We are looking at this and will respond soon.

**Comment by jeff-da** [comment]
Hi, for `eval.py`, could you try using `system_eval/automatic_eval.py` as referenced in the previous issue? BLEU-4 calculated the n-gram scores for BLEU-1, 2, 3 and averages them for the final score. For detail, please refer to https://github.com/allenai/comet-atomic-2020/blob/9b73049abbad282f80e4fca233a38b9d43ac0ffa/evaluation/bleu/bleu_scorer.py#L199.
